// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebFlex.UI.Data;

#nullable disable

namespace WebFlex.UI.Migrations
{
    [DbContext(typeof(WebFlexDbContext))]
    [Migration("20260623080520_model_001")]
    partial class model_001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SMenu", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("menu_id")
                        .HasColumnOrder(1);

                    b.Property<string>("ACTION_NAME")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_name")
                        .HasColumnOrder(15)
                        .HasComment("액션명");

                    b.Property<string>("CONTROLLER_NAME")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("controller_name")
                        .HasColumnOrder(14)
                        .HasComment("컨트롤러명");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ICON")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon")
                        .HasColumnOrder(17)
                        .HasComment("아이콘");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MENU_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("menu_code")
                        .HasColumnOrder(12)
                        .HasComment("메뉴 코드");

                    b.Property<string>("MENU_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("menu_name")
                        .HasColumnOrder(13)
                        .HasComment("메뉴명");

                    b.Property<string>("PARENT_MENU_ID")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("parent_menu_id")
                        .HasColumnOrder(11)
                        .HasComment("상위 메뉴 아이디");

                    b.Property<bool>("SHOW_IN_MENU")
                        .HasColumnType("boolean")
                        .HasColumnName("show_in_menu")
                        .HasColumnOrder(19)
                        .HasComment("메뉴 표시 여부");

                    b.Property<int?>("SORT_ORDER")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasColumnOrder(18)
                        .HasComment("정렬 순서");

                    b.Property<string>("URL")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("url")
                        .HasColumnOrder(16)
                        .HasComment("URL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ID")
                        .HasName("pk_s_menu");

                    b.HasIndex("PARENT_MENU_ID")
                        .HasDatabaseName("ix_s_menu_parent_menu_id");

                    b.ToTable("s_menu", null, t =>
                        {
                            t.HasComment("시스템 메뉴 정보");
                        });
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SRole", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("role_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DESCRIPTION")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasColumnOrder(13)
                        .HasComment("설명");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ROLE_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_code")
                        .HasColumnOrder(11)
                        .HasComment("권한 코드");

                    b.Property<string>("ROLE_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_name")
                        .HasColumnOrder(12)
                        .HasComment("권한명");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ID")
                        .HasName("pk_s_role");

                    b.ToTable("s_role", null, t =>
                        {
                            t.HasComment("시스템 권한 정보");
                        });
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SRoleMenu", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("role_menu_id")
                        .HasColumnOrder(1);

                    b.Property<bool>("CAN_CREATE")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create")
                        .HasColumnOrder(14)
                        .HasComment("생성 권한");

                    b.Property<bool>("CAN_DELETE")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete")
                        .HasColumnOrder(16)
                        .HasComment("삭제 권한");

                    b.Property<bool>("CAN_EXPORT")
                        .HasColumnType("boolean")
                        .HasColumnName("can_export")
                        .HasColumnOrder(17)
                        .HasComment("내보내기 권한");

                    b.Property<bool>("CAN_READ")
                        .HasColumnType("boolean")
                        .HasColumnName("can_read")
                        .HasColumnOrder(13)
                        .HasComment("조회 권한");

                    b.Property<bool>("CAN_UPDATE")
                        .HasColumnType("boolean")
                        .HasColumnName("can_update")
                        .HasColumnOrder(15)
                        .HasComment("수정 권한");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MENU_ID")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("menu_id")
                        .HasColumnOrder(12)
                        .HasComment("메뉴 아이디");

                    b.Property<string>("ROLE_ID")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("role_id")
                        .HasColumnOrder(11)
                        .HasComment("권한 아이디");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ID")
                        .HasName("pk_s_role_menu");

                    b.HasIndex("MENU_ID")
                        .HasDatabaseName("ix_s_role_menu_menu_id");

                    b.HasIndex("ROLE_ID")
                        .HasDatabaseName("ix_s_role_menu_role_id");

                    b.ToTable("s_role_menu", null, t =>
                        {
                            t.HasComment("시스템 권한별 메뉴 정보");
                        });
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SUser", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("user_uid")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EMAIL")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email")
                        .HasColumnOrder(14)
                        .HasComment("이메일");

                    b.Property<bool>("IS_ADMIN")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin")
                        .HasColumnOrder(16)
                        .HasComment("관리자 여부");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LAST_LOGIN_AT")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at")
                        .HasColumnOrder(17)
                        .HasComment("마지막 로그인 일시");

                    b.Property<string>("PASSWORD_HASH")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash")
                        .HasColumnOrder(13)
                        .HasComment("비밀번호 해시");

                    b.Property<string>("PHONE_NUMBER")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number")
                        .HasColumnOrder(15)
                        .HasComment("전화번호");

                    b.Property<string>("USER_ID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id")
                        .HasColumnOrder(11)
                        .HasComment("사용자 아이디");

                    b.Property<string>("USER_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name")
                        .HasColumnOrder(12)
                        .HasComment("사용자명");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ID")
                        .HasName("pk_s_user");

                    b.ToTable("s_user", null, t =>
                        {
                            t.HasComment("시스템 사용자 정보");
                        });
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SUserRole", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("user_role_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ROLE_ID")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("role_id")
                        .HasColumnOrder(12)
                        .HasComment("권한 아이디");

                    b.Property<string>("USER_UID")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("user_uid")
                        .HasColumnOrder(11)
                        .HasComment("사용자 고유 아이디");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ID")
                        .HasName("pk_s_user_role");

                    b.HasIndex("ROLE_ID")
                        .HasDatabaseName("ix_s_user_role_role_id");

                    b.HasIndex("USER_UID")
                        .HasDatabaseName("ix_s_user_role_user_uid");

                    b.ToTable("s_user_role", null, t =>
                        {
                            t.HasComment("시스템 사용자별 권한 정보");
                        });
                });

            modelBuilder.Entity("WebFlex.Shared.OpcClientOption", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("client_option_id")
                        .HasColumnOrder(1);

                    b.Property<string>("CONFIGURED_OPTION_NAMES")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("configured_option_names")
                        .HasColumnOrder(14)
                        .HasComment("설정된 옵션명 목록");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DESCRIPTION")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasColumnOrder(15)
                        .HasComment("설명");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("OPTION_CODE")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("option_code")
                        .HasColumnOrder(11)
                        .HasComment("옵션 코드");

                    b.Property<string>("OPTION_JSON")
                        .HasColumnType("text")
                        .HasColumnName("option_json")
                        .HasColumnOrder(13)
                        .HasComment("옵션 JSON");

                    b.Property<string>("OPTION_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("option_name")
                        .HasColumnOrder(12)
                        .HasComment("옵션명");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ID")
                        .HasName("pk_opc_client_option");

                    b.ToTable("opc_client_option", null, t =>
                        {
                            t.HasComment("OPC 클라이언트 옵션");
                        });
                });

            modelBuilder.Entity("WebFlex.Shared.OpcCollectOption", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("collect_option_id")
                        .HasColumnOrder(1);

                    b.Property<bool>("AUTO_RECONNECT")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_reconnect")
                        .HasColumnOrder(18)
                        .HasComment("자동 재연결 여부");

                    b.Property<int?>("CONNECTION_CHECK_INTERVAL_SECONDS")
                        .HasColumnType("integer")
                        .HasColumnName("connection_check_interval_seconds")
                        .HasColumnOrder(20)
                        .HasComment("연결 확인 주기(초)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DESCRIPTION")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasColumnOrder(21)
                        .HasComment("설명");

                    b.Property<int?>("FLUSH_INTERVAL_MILLISECONDS")
                        .HasColumnType("integer")
                        .HasColumnName("flush_interval_milliseconds")
                        .HasColumnOrder(15)
                        .HasComment("Flush 주기(ms)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int?>("MAX_BATCH_SIZE")
                        .HasColumnType("integer")
                        .HasColumnName("max_batch_size")
                        .HasColumnOrder(16)
                        .HasComment("최대 배치 크기");

                    b.Property<string>("OPTION_CODE")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("option_code")
                        .HasColumnOrder(11)
                        .HasComment("옵션 코드");

                    b.Property<string>("OPTION_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("option_name")
                        .HasColumnOrder(12)
                        .HasComment("옵션명");

                    b.Property<int?>("RECONNECT_INTERVAL_SECONDS")
                        .HasColumnType("integer")
                        .HasColumnName("reconnect_interval_seconds")
                        .HasColumnOrder(19)
                        .HasComment("재연결 주기(초)");

                    b.Property<int?>("RELOAD_INTERVAL_SECONDS")
                        .HasColumnType("integer")
                        .HasColumnName("reload_interval_seconds")
                        .HasColumnOrder(13)
                        .HasComment("수집 대상 재조회 주기(초)");

                    b.Property<int?>("SAVE_INTERVAL_MILLISECONDS")
                        .HasColumnType("integer")
                        .HasColumnName("save_interval_milliseconds")
                        .HasColumnOrder(14)
                        .HasComment("저장 주기(ms)");

                    b.Property<bool>("SAVE_ONLY_CHANGED_VALUE")
                        .HasColumnType("boolean")
                        .HasColumnName("save_only_changed_value")
                        .HasColumnOrder(17)
                        .HasComment("변경값만 저장 여부");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ID")
                        .HasName("pk_opc_collect_option");

                    b.ToTable("opc_collect_option", null, t =>
                        {
                            t.HasComment("OPC 수집 옵션");
                        });
                });

            modelBuilder.Entity("WebFlex.Shared.OpcCollectRuntimeStatus", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("runtime_status_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DEVICE_ID")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("device_id")
                        .HasColumnOrder(11)
                        .HasComment("디바이스 아이디");

                    b.Property<string>("ENDPOINT_URL")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint_url")
                        .HasColumnOrder(12)
                        .HasComment("Endpoint URL");

                    b.Property<bool>("IS_CONNECTED")
                        .HasColumnType("boolean")
                        .HasColumnName("is_connected")
                        .HasColumnOrder(13)
                        .HasComment("연결 여부");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LAST_CONNECTED_AT")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connected_at")
                        .HasColumnOrder(15)
                        .HasComment("마지막 연결 일시");

                    b.Property<DateTime?>("LAST_DISCONNECTED_AT")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_disconnected_at")
                        .HasColumnOrder(16)
                        .HasComment("마지막 연결 해제 일시");

                    b.Property<string>("LAST_ERROR_MESSAGE")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error_message")
                        .HasColumnOrder(18)
                        .HasComment("마지막 오류 메시지");

                    b.Property<DateTime?>("LAST_RECEIVED_AT")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_received_at")
                        .HasColumnOrder(17)
                        .HasComment("마지막 수신 일시");

                    b.Property<DateTime?>("STATUS_UPDATED_AT")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_updated_at")
                        .HasColumnOrder(19)
                        .HasComment("상태 갱신 일시");

                    b.Property<int?>("SUBSCRIBED_COUNT")
                        .HasColumnType("integer")
                        .HasColumnName("subscribed_count")
                        .HasColumnOrder(14)
                        .HasComment("구독 태그 수");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ID")
                        .HasName("pk_opc_collect_runtime_status");

                    b.HasIndex("DEVICE_ID")
                        .HasDatabaseName("ix_opc_collect_runtime_status_device_id");

                    b.ToTable("opc_collect_runtime_status", null, t =>
                        {
                            t.HasComment("OPC 수집 런타임 상태");
                        });
                });

            modelBuilder.Entity("WebFlex.Shared.OpcDevice", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("device_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DESCRIPTION")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasColumnOrder(33)
                        .HasComment("설명");

                    b.Property<string>("DEVICE_ADDRESS")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_address")
                        .HasColumnOrder(13)
                        .HasComment("디바이스 주소");

                    b.Property<string>("DEVICE_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_name")
                        .HasColumnOrder(12)
                        .HasComment("디바이스명");

                    b.Property<string>("DEVICE_TYPE")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("device_type")
                        .HasColumnOrder(16)
                        .HasComment("디바이스 타입");

                    b.Property<string>("ENDPOINT_URL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint_url")
                        .HasColumnOrder(15)
                        .HasComment("Endpoint URL");

                    b.Property<bool>("IS_COLLECTENABLED")
                        .HasColumnType("boolean")
                        .HasColumnName("is_collectenabled")
                        .HasColumnOrder(17)
                        .HasComment("수집 사용 여부");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("OpcGroupID")
                        .HasColumnType("text")
                        .HasColumnName("opc_group_id");

                    b.Property<string>("PASSWORD")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password")
                        .HasColumnOrder(38)
                        .HasComment("OPC 서버 접속 비밀번호");

                    b.Property<int?>("PORT")
                        .HasColumnType("integer")
                        .HasColumnName("port")
                        .HasColumnOrder(14)
                        .HasComment("포트");

                    b.Property<int?>("PUBLISHINGINTERVALMS")
                        .HasColumnType("integer")
                        .HasColumnName("publishingintervalms")
                        .HasColumnOrder(31)
                        .HasComment("Publishing Interval(ms)");

                    b.Property<int?>("SAMPLINGINTERVALMS")
                        .HasColumnType("integer")
                        .HasColumnName("samplingintervalms")
                        .HasColumnOrder(32)
                        .HasComment("Sampling Interval(ms)");

                    b.Property<string>("SECURITYMODE")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("securitymode")
                        .HasColumnOrder(35)
                        .HasComment("보안 모드");

                    b.Property<string>("SECURITYPOLICY")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("securitypolicy")
                        .HasColumnOrder(36)
                        .HasComment("보안 정책");

                    b.Property<string>("USER_NAME")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name")
                        .HasColumnOrder(37)
                        .HasComment("OPC 서버 접속 사용자명");

                    b.Property<bool>("USESECURITY")
                        .HasColumnType("boolean")
                        .HasColumnName("usesecurity")
                        .HasColumnOrder(34)
                        .HasComment("보안 사용 여부");

                    b.Property<bool>("USE_ANONYMOUS")
                        .HasColumnType("boolean")
                        .HasColumnName("use_anonymous")
                        .HasColumnOrder(30)
                        .HasComment("익명 접속 사용 여부");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ID")
                        .HasName("pk_opc_device");

                    b.HasIndex("OpcGroupID")
                        .HasDatabaseName("ix_opc_device_opc_group_id");

                    b.ToTable("opc_device", null, t =>
                        {
                            t.HasComment("디바이스 정보");
                        });
                });

            modelBuilder.Entity("WebFlex.Shared.OpcGroup", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("group_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DESCRIPTION")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasColumnOrder(15)
                        .HasComment("설명");

                    b.Property<string>("GROUP_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("group_name")
                        .HasColumnOrder(13)
                        .HasComment("그룹명");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MAJOR_GROUP_ID")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("major_group_id")
                        .HasColumnOrder(11)
                        .HasComment("대그룹 아이디");

                    b.Property<int?>("SORT_ORDER")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasColumnOrder(14)
                        .HasComment("정렬 순서");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ID")
                        .HasName("pk_opc_group");

                    b.HasIndex("MAJOR_GROUP_ID")
                        .HasDatabaseName("ix_opc_group_major_group_id");

                    b.ToTable("opc_group", null, t =>
                        {
                            t.HasComment("OPC 중그룹 정보");
                        });
                });

            modelBuilder.Entity("WebFlex.Shared.OpcMajorGroup", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("major_group_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DESCRIPTION")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasColumnOrder(14)
                        .HasComment("설명");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MAJOR_GROUP_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("major_group_name")
                        .HasColumnOrder(12)
                        .HasComment("대그룹명");

                    b.Property<int?>("SORT_ORDER")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasColumnOrder(13)
                        .HasComment("정렬 순서");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ID")
                        .HasName("pk_opc_major_group");

                    b.ToTable("opc_major_group", null, t =>
                        {
                            t.HasComment("OPC 대그룹 정보");
                        });
                });

            modelBuilder.Entity("WebFlex.Shared.OpcTag", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("tag_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DATA_TYPE")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("data_type")
                        .HasColumnOrder(17)
                        .HasComment("데이터 타입");

                    b.Property<string>("DESCRIPTION")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasColumnOrder(24)
                        .HasComment("설명");

                    b.Property<string>("DEVICE_ID")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("device_id")
                        .HasColumnOrder(11)
                        .HasComment("디바이스 아이디");

                    b.Property<string>("GROUP_ID")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("group_id")
                        .HasColumnOrder(13)
                        .HasComment("중그룹 아이디");

                    b.Property<bool>("IS_COLLECTENABLED")
                        .HasColumnType("boolean")
                        .HasColumnName("is_collectenabled")
                        .HasColumnOrder(18)
                        .HasComment("수집 사용 여부");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("NODE_ID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("node_id")
                        .HasColumnOrder(12)
                        .HasComment("노드 아이디");

                    b.Property<int?>("SAMPLINGINTERVALMS")
                        .HasColumnType("integer")
                        .HasColumnName("samplingintervalms")
                        .HasColumnOrder(21)
                        .HasComment("Sampling Interval(ms)");

                    b.Property<bool>("SAVE_TO_DATABASE")
                        .HasColumnType("boolean")
                        .HasColumnName("save_to_database")
                        .HasColumnOrder(19)
                        .HasComment("DB 저장 여부");

                    b.Property<bool>("SHOW_ON_DASHBOARD")
                        .HasColumnType("boolean")
                        .HasColumnName("show_on_dashboard")
                        .HasColumnOrder(20)
                        .HasComment("대시보드 표시 여부");

                    b.Property<int?>("SORT_ORDER")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasColumnOrder(23)
                        .HasComment("정렬 순서");

                    b.Property<string>("TAG_NAME")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tag_name")
                        .HasColumnOrder(15)
                        .HasComment("표시명");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ID")
                        .HasName("pk_opc_tag");

                    b.HasIndex("DEVICE_ID")
                        .HasDatabaseName("ix_opc_tag_device_id");

                    b.HasIndex("GROUP_ID")
                        .HasDatabaseName("ix_opc_tag_group_id");

                    b.ToTable("opc_tag", null, t =>
                        {
                            t.HasComment("OPC 태그 정보");
                        });
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SMenu", b =>
                {
                    b.HasOne("WebFlex.Shared.Entities.System.SMenu", "ParentMenu")
                        .WithMany("ChildrenMenus")
                        .HasForeignKey("PARENT_MENU_ID")
                        .HasConstraintName("fk_s_menu_s_menu_parent_menu_id");

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SRoleMenu", b =>
                {
                    b.HasOne("WebFlex.Shared.Entities.System.SMenu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MENU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_s_role_menu_s_menu_menu_id");

                    b.HasOne("WebFlex.Shared.Entities.System.SRole", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("ROLE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_s_role_menu_s_role_role_id");

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SUserRole", b =>
                {
                    b.HasOne("WebFlex.Shared.Entities.System.SRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("ROLE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_s_user_role_s_role_role_id");

                    b.HasOne("WebFlex.Shared.Entities.System.SUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("USER_UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_s_user_role_s_user_user_uid");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebFlex.Shared.OpcCollectRuntimeStatus", b =>
                {
                    b.HasOne("WebFlex.Shared.OpcDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DEVICE_ID")
                        .HasConstraintName("fk_opc_collect_runtime_status_opc_device_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("WebFlex.Shared.OpcDevice", b =>
                {
                    b.HasOne("WebFlex.Shared.OpcGroup", null)
                        .WithMany("Devices")
                        .HasForeignKey("OpcGroupID")
                        .HasConstraintName("fk_opc_device_opc_group_opc_group_id");
                });

            modelBuilder.Entity("WebFlex.Shared.OpcGroup", b =>
                {
                    b.HasOne("WebFlex.Shared.OpcMajorGroup", "MajorGroup")
                        .WithMany("Groups")
                        .HasForeignKey("MAJOR_GROUP_ID")
                        .HasConstraintName("fk_opc_group_opc_major_group_major_group_id");

                    b.Navigation("MajorGroup");
                });

            modelBuilder.Entity("WebFlex.Shared.OpcTag", b =>
                {
                    b.HasOne("WebFlex.Shared.OpcDevice", "Device")
                        .WithMany("Tags")
                        .HasForeignKey("DEVICE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opc_tag_opc_device_device_id");

                    b.HasOne("WebFlex.Shared.OpcGroup", "Group")
                        .WithMany("Tags")
                        .HasForeignKey("GROUP_ID")
                        .HasConstraintName("fk_opc_tag_opc_group_group_id");

                    b.Navigation("Device");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SMenu", b =>
                {
                    b.Navigation("ChildrenMenus");

                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SRole", b =>
                {
                    b.Navigation("RoleMenus");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WebFlex.Shared.OpcDevice", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("WebFlex.Shared.OpcGroup", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("WebFlex.Shared.OpcMajorGroup", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
