// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebFlex.UI.Data;

#nullable disable

namespace WebFlex.UI.Migrations
{
    [DbContext(typeof(WebFlexDbContext))]
    partial class WebFlexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebFlex.Shared.Entities.Opc.OpcCollectOption", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("AutoReconnect")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_reconnect");

                    b.Property<int>("ConnectionCheckIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("connection_check_interval_seconds");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FlushIntervalMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("flush_interval_milliseconds");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("MaxBatchSize")
                        .HasColumnType("integer")
                        .HasColumnName("max_batch_size");

                    b.Property<string>("OptionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("option_code");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("option_name");

                    b.Property<int>("ReconnectIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("reconnect_interval_seconds");

                    b.Property<int>("ReloadIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("reload_interval_seconds");

                    b.Property<int>("SaveIntervalMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("save_interval_milliseconds");

                    b.Property<bool>("SaveOnlyChangedValue")
                        .HasColumnType("boolean")
                        .HasColumnName("save_only_changed_value");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OptionCode")
                        .IsUnique();

                    b.ToTable("opc_collect_option", (string)null);
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.Opc.OpcCollectRuntimeStatus", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endpoint_url");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_connected");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connected_at");

                    b.Property<DateTime?>("LastDisconnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_disconnected_at");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<DateTime?>("LastReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_received_at");

                    b.Property<string>("OpcDeviceId")
                        .HasColumnType("text")
                        .HasColumnName("opc_device_id");

                    b.Property<DateTime>("StatusUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_updated_at");

                    b.Property<int>("SubscribedCount")
                        .HasColumnType("integer")
                        .HasColumnName("subscribed_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EndpointUrl")
                        .IsUnique();

                    b.HasIndex("OpcDeviceId");

                    b.ToTable("opc_collect_runtime_status", (string)null);
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.Opc.OpcDevice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DeviceAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_address");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_code");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_type");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endpoint_url");

                    b.Property<bool>("IsCollectEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_collect_enabled");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("OpcGroupId")
                        .HasColumnType("text")
                        .HasColumnName("opc_group_id");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<int>("PublishingIntervalMs")
                        .HasColumnType("integer")
                        .HasColumnName("publishing_interval_ms");

                    b.Property<int>("QueueSize")
                        .HasColumnType("integer")
                        .HasColumnName("queue_size");

                    b.Property<int>("SamplingIntervalMs")
                        .HasColumnType("integer")
                        .HasColumnName("sampling_interval_ms");

                    b.Property<string>("SecurityMode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_mode");

                    b.Property<string>("SecurityPolicy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_policy");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("use_anonymous");

                    b.Property<bool>("UseSecurity")
                        .HasColumnType("boolean")
                        .HasColumnName("use_security");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("EndpointUrl")
                        .IsUnique();

                    b.HasIndex("OpcGroupId");

                    b.ToTable("opc_device", (string)null);
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.Opc.OpcGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("group_code");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("OpcMajorGroupId")
                        .HasColumnType("text")
                        .HasColumnName("opc_major_group_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GroupCode")
                        .IsUnique();

                    b.HasIndex("OpcMajorGroupId");

                    b.ToTable("opc_group", (string)null);
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.Opc.OpcMajorGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MajorGroupCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("major_group_code");

                    b.Property<string>("MajorGroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("major_group_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MajorGroupCode")
                        .IsUnique();

                    b.ToTable("opc_major_group", (string)null);
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.Opc.OpcTag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("data_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("display_name");

                    b.Property<string>("GroupName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("group_name");

                    b.Property<bool>("IsCollectEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_collect_enabled");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("node_id");

                    b.Property<string>("OpcDeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opc_device_id");

                    b.Property<string>("OpcGroupId")
                        .HasColumnType("text")
                        .HasColumnName("opc_group_id");

                    b.Property<int?>("QueueSize")
                        .HasColumnType("integer")
                        .HasColumnName("queue_size");

                    b.Property<int?>("SamplingIntervalMs")
                        .HasColumnType("integer")
                        .HasColumnName("sampling_interval_ms");

                    b.Property<bool>("SaveToDatabase")
                        .HasColumnType("boolean")
                        .HasColumnName("save_to_database");

                    b.Property<bool>("ShowOnDashboard")
                        .HasColumnType("boolean")
                        .HasColumnName("show_on_dashboard");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TagCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tag_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OpcGroupId");

                    b.HasIndex("TagCode");

                    b.HasIndex("OpcDeviceId", "NodeId")
                        .IsUnique();

                    b.ToTable("opc_tag", (string)null);
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SMenu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActionName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_name");

                    b.Property<string>("ControllerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("controller_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MenuCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("menu_code");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("menu_name");

                    b.Property<string>("ParentMenuId")
                        .HasColumnType("text")
                        .HasColumnName("parent_menu_id");

                    b.Property<bool>("ShowInMenu")
                        .HasColumnType("boolean")
                        .HasColumnName("show_in_menu");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("MenuCode")
                        .IsUnique();

                    b.HasIndex("ParentMenuId");

                    b.ToTable("s_menu", (string)null);
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_code");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RoleCode")
                        .IsUnique();

                    b.ToTable("s_role", (string)null);
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SRoleMenu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete");

                    b.Property<bool>("CanExport")
                        .HasColumnType("boolean")
                        .HasColumnName("can_export");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean")
                        .HasColumnName("can_read");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("boolean")
                        .HasColumnName("can_update");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("SMenuId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("s_menu_id");

                    b.Property<string>("SRoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("s_role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SMenuId");

                    b.HasIndex("SRoleId", "SMenuId")
                        .IsUnique();

                    b.ToTable("s_role_menu", (string)null);
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("s_user", (string)null);
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SUserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("SRoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("s_role_id");

                    b.Property<string>("SUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("s_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SRoleId");

                    b.HasIndex("SUserId", "SRoleId")
                        .IsUnique();

                    b.ToTable("s_user_role", (string)null);
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.Opc.OpcCollectRuntimeStatus", b =>
                {
                    b.HasOne("WebFlex.Shared.Entities.Opc.OpcDevice", "Device")
                        .WithMany()
                        .HasForeignKey("OpcDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.Opc.OpcDevice", b =>
                {
                    b.HasOne("WebFlex.Shared.Entities.Opc.OpcGroup", "Group")
                        .WithMany("Devices")
                        .HasForeignKey("OpcGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.Opc.OpcGroup", b =>
                {
                    b.HasOne("WebFlex.Shared.Entities.Opc.OpcMajorGroup", "MajorGroup")
                        .WithMany("Groups")
                        .HasForeignKey("OpcMajorGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MajorGroup");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.Opc.OpcTag", b =>
                {
                    b.HasOne("WebFlex.Shared.Entities.Opc.OpcDevice", "Device")
                        .WithMany("Tags")
                        .HasForeignKey("OpcDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebFlex.Shared.Entities.Opc.OpcGroup", "Group")
                        .WithMany("Tags")
                        .HasForeignKey("OpcGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SMenu", b =>
                {
                    b.HasOne("WebFlex.Shared.Entities.System.SMenu", "ParentMenu")
                        .WithMany("Children")
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SRoleMenu", b =>
                {
                    b.HasOne("WebFlex.Shared.Entities.System.SMenu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("SMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebFlex.Shared.Entities.System.SRole", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("SRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SUserRole", b =>
                {
                    b.HasOne("WebFlex.Shared.Entities.System.SRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("SRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebFlex.Shared.Entities.System.SUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("SUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.Opc.OpcDevice", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.Opc.OpcGroup", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.Opc.OpcMajorGroup", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SMenu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SRole", b =>
                {
                    b.Navigation("RoleMenus");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WebFlex.Shared.Entities.System.SUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
